# Generated by Django 3.1.2 on 2020-12-20 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201220_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='voter_id',
            field=models.CharField(default=124578963, max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='voter',
        ),
    ]
